services:
  mymongo:
    image: mongo

  dbbrowser:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mymongo
    depends_on:
      - mymongo
    
  api:
    build: ./checker
    image: myapp:1.0.0
    depends_on:
      - mymongo

  web:
    build: ./plot
    image: plot
    depends_on:
      - api
    ports:
      - 127.0.0.1:5000:5000